"""empty message

Revision ID: 1b92044839a7
Revises: None
Create Date: 2014-09-13 13:08:04.413536

"""

# revision identifiers, used by Alembic.
revision = '1b92044839a7'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
