"""empty message

Revision ID: 8d3663dccb8
Revises: 2900f0d72dd2
Create Date: 2014-09-28 08:31:02.351655

"""

# revision identifiers, used by Alembic.
revision = '8d3663dccb8'
down_revision = '2900f0d72dd2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'email')
    ### end Alembic commands ###
